version: '3'

services:
   postgres:
    image: postgis/postgis
  # image: postgres:14.0
    # container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGPASSWORD: ${PG_ROOT_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgis-store:/var/lib/postgresql/data
      # - ./docker/postgresql/data:/var/lib/postgresql/data
      - ./docker/postgresql/initdb:/docker-entrypoint-initdb.d
volumes:
        postgis-store:
