version: "3"

services:
    db:
       image: mysql:8.0
       volumes:
        # - mysql-store:/var/lib/mysql      
         - ./docker/mysql/data:/var/lib/mysql
         - ./docker/mysql/logs:/var/log/mysql
         - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
       environment:
         - MYSQL_DATABASE=POC
         - MYSQL_USER=admin
         - MYSQL_PASSWORD=password
         - MYSQL_ROOT_PASSWORD=password
         - TZ="Asia/Tokyo"
      #command: mysqld --character-set-server=utf8mb4 
       ports:
         - 13306:3306
#volumes:
#  mysql-store:
